# helm/zabbix-values.yaml
zabbixServer:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m        # reduced from 200m
      memory: 128Mi    # reduced from 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
 
zabbixWeb:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  service:
    type: ClusterIP  # changed from ClusterIP so you get a public IP
    port: 80
 
zabbixAgent:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
 
postgresql:
  enabled: true
  auth:
    database: zabbix
    username: zabbix
    existingSecret: zabbix-db-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "managed-csi"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
 
zabbixProxy:
  enabled: false